replicaCount: 2

ingress:
  host: staging.example.com
  certificateArn: ""

env:
  API_BASE_URL: http://api:8000
  AUTH_URL: https://staging.example.com
  APP_URL: https://staging.example.com

secrets: {}
