image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

storage:
  size: 1Gi

credentials:
  database: fullstack_monorepo_dev
  username: postgres
  password: password

service:
  port: 5432
